#!/bin/bash
function moduleRun() {
    if [ $# -gt 0 ]; then
        $GIT branch "$@"
        return
    fi
	local branches=(`$GIT for-each-ref --sort=committerdate refs/heads/ --format='%(refname:short)'`)

	for branch in "${branches[@]}"; do
		if [ "$branch" == "$BRANCH" ]; then
			echoGreen "* $branch " -n
		else
			echo -n "  $branch "
		fi
		echoViolet " `$GIT config branch.$branch.note`"
	done
}
