#!/bin/bash
function moduleRun() {
    if [ $# -gt 0 ]; then
        $GIT branch "$@"
        return
    fi
	local branches=(`$GIT for-each-ref --sort=committerdate refs/heads/ --format='%(refname:short)'`)

	for branch in "${branches[@]}"; do
		if [ "$branch" == "$BRANCH" ]; then
			echo -n `green "* $branch "`
		else
			echo -n "  $branch "
		fi
		echo $(magenta " `$GIT config branch.$branch.note`")
	done
}
