#!/bin/bash
function moduleRun() {
    vbc="$BRANCH"
    vbc_col=$(( $($GIT show-branch | grep '^[^\[]*\*' | head -1 | cut -d* -f1 | wc -c) - 1 ))
    swimming_lane_start_row=$(( $($GIT show-branch | grep -n "^[\-]*$" | cut -d: -f1) + 1 ))
    $GIT show-branch | tail -n +$swimming_lane_start_row | grep -v "^[^\[]*\[$vbc" | grep "^.\{$vbc_col\}[^ ]" | head -n1 | sed 's/.*\[\(.*\)\].*/\1/' | sed 's/[\^~].*//'
}
