#!/bin/bash
function moduleLoadOptions() {
    getOpt "-a" get_all
    getOpt "-s" status
    return 0
}

function prs() {
    gh pr --json baseRefName,headRefName,reviewDecision,url,title,mergeable,mergeStateStatus,isDraft,reviewRequests,statusCheckRollup "$@"
}

function moduleRun() {
    if $status; then
        node __ROOT__/js/printPRs.js "`prs view`"
    elif $get_all; then
        repos=(`gh api -X GET search/issues -f q='author:RaffaeleCanale type:pr state:open' | jq -r .items[].url | sed -e 's@^https://api.github.com/repos/\(.*\)/issues/.*@\1@' | sort | uniq`)
        for repo in "${repos[@]}"; do
            echo `bold "$repo"`
            node __ROOT__/js/printPRs.js "`prs list -R "$repo" -A RaffaeleCanale`"
        done
    else
        node __ROOT__/js/printPRs.js "`prs list`"
    fi
}
