#!/bin/bash
function remoteExists() {
    git branch -a | egrep "remotes/origin/${1:-$BRANCH}$" > /dev/null
}

function moduleRun() {
    if [ "$BRANCH" == "develop" ] || [ "$BRANCH" == "staging" ] || [ "$BRANCH" == "master" ]; then
        # if ! inputYesNo "`red "Are you sure you want to push to $BRANCH?"`"; then
        if ! inputYesNo "Are you sure you want to push to `red "$BRANCH"`?"; then
            stop "Cancelled"
        fi
    fi
    MERGE_REGEX_1="Merge branch .* into .*"
    MERGE_REGEX_2="Merge pull request .* from .*"

    if remoteExists; then
        # getCommits | while read commit; do
        #     if ! [[ "$commit" =~ $MERGE_REGEX_1 ]] && ! [[ "$commit" =~ $MERGE_REGEX_2 ]]; then
        #         if ! [[ "$commit" =~ __PROJECT_REGEX__ ]]; then
        #             error "Missing ticket number: $commit"
        #         fi
        #         message="`getCommitMessage "$commit"`"

        #         if [ "$message" == "wip" ]; then
        #             error "Forbidden commit message: $commit"
        #         fi
        #     fi
        # done || exit 1

        # getCommits | while read commit; do
        #     echo `yellow "  $commit"`
        # done

        # read -p ""
        $GIT push "$@"
    else
        ARGUMENTS+=("--set-upstream")
        ARGUMENTS+=("origin")
        ARGUMENTS+=("$BRANCH")
        echo "cmd: git push ${ARGUMENTS[@]}"

        read -p ""
        $GIT push "${ARGUMENTS[@]}"
    fi
}
